### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by zsociety** [lhbizarro/bruno-arizio#8]
Am I doing something wrong? Any tips for this issue?  I've configured prismic and followed your instructions but getting this error. 

const [_, endpoint] = process.env.PRISMIC_ENDPOINT.match(repoRegexp);

TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
 at Object.trigger (/bruno-arizio-master/onboarding.js:5:25)
[0]     at Server.<anonymous> (bruno-arizio-master/app.js:53:14)
[0]     at Object.onceWrapper (events.js:421:28)
[0]     at Server.emit (events.js:315:20)
[0]     at emitListeningNT (net.js:1347:10)
[0]     at processTicksAndRejections (internal/process/task_queues.js:83:21)

**Comment by studiookkult** [comment]
@zsociety I've got the same Issue. Did you get it to work?

@lhbizarro Can you help us with this? Thanks in advance.

**Comment by lhbizarro** [comment]
@studiookkult the solution for that is removing the `.match(repoRegexp);` and just keeping it as: `const endpoint = process.env.PRISMIC_ENDPOINT;`. I think the previous implementation got replaced by Prismic team, which made this repository slightly outdated.

**Comment by zsociety** [comment]
> @zsociety I've got the same Issue. Did you get it to work?
> 
> @lhbizarro Can you help us with this? Thanks in advance.

@studiookkult  
I didn't fixed it :(

**Comment by Afvanjaffer** [comment]
> @studiookkult the solution for that is removing the `.match(repoRegexp);` and just keeping it as: `const endpoint = process.env.PRISMIC_ENDPOINT;`. I think the previous implementation got replaced by Prismic team, which made this repository slightly outdated.

it didnt fix it

**Comment by Afvanjaffer** [comment]
Error: Invalid URI
